Algoritmo "Exercicio2"
// Aluno: Eduardo Iwao Garcia Reis Kunihiro
// Turma: 2UNB
// RA: 02610280
Var
n1: inteiro
n2: inteiro
Inicio
escreval("|=|========|=|PROGRAMA INICIALIZADO|=|========|=|")
escreval("Informe o primeiro número (inteiro):")
leia(n1)
escreval("Informe o segundo número (inteiro)")
leia(n2)
escreval("|=|========|=|OPERAÇÕES|=|========|=|")
escreval("Soma: ",n1," +",n2," =",n1+n2)
escreval("Subtração: ",n1," -",n2," =",n1-n2)
escreval("Multiplicação: ",n1," X",n2," =",n1*n2)
escreval("Divisão: ",n1," /",n2," =",n1/n2)
Fimalgoritmo