Algoritmo "Exercicio1"
// Aluno: Eduardo Iwao Garcia Reis Kunihiro
// Turma: 2UNB
// RA: 02610280
Var
nome: caractere
idade: inteiro
Inicio
escreval("|=|========|=|PROGRAMA INICIALIZADO|=|========|=|")
escreval("Informe seu nome:")
leia(nome)
escreval("Informe sua idade")
leia(idade)
escreval("|=|========|=|DADOS|=|========|=|")
escreval("Nome Registrado:",nome)
escreval("Idade Registrada:",idade)
escreval("Bem vindo ao sistema")

Fimalgoritmo