Algoritmo "Exercicio4"
// Aluno: Eduardo Iwao Garcia Reis Kunihiro
// Turma: 2UNB
// RA: 02610280
Var
n1: real
Inicio
escreval("|=|========|=|PROGRAMA INICIALIZADO|=|========|=|")
escreval("Informe o numero:")
leia(n1)
escreval("|=|========|=|RESULTADO|=|========|=|")

se n1 = 0 entao
   escreval("Número NULO")
senao
   se n1  >0 entao
      escreval("Número POSITIVO")
   senao
      escreval("Número NEGATIVO")
   fimse
fimse
Fimalgoritmo