Algoritmo "Exercicio14"
// Aluno: Eduardo Iwao Garcia Reis Kunihiro
// Turma: 2UNB
// RA: 02610280

Var
   n1: inteiro
   x: inteiro
Inicio

   escreval("|=|========|=|PROGRAMA INICIALIZADO|=|========|=|")
   
   escreval("Informe o número para a tabuada:")
   leia(n1)

   escreval("|=|========|=|RESULTADO|=|========|=|")
   para x de 1 ate 10 faca
        escreval(n1," x",x," = ",n1*x)
   fimpara
Fimalgoritmo